name: community
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  slimy_card: ^1.0.4
  device_preview: ^0.5.5
  flutter_staggered_grid_view: ^0.3.2
  firebase_storage: ^3.1.3
  image_picker: ^0.6.0+2
  flutter_icons: ^1.1.0
  # firebase_core: ^0.3.0
  
  
  
  shimmer: ^1.1.2
  curved_navigation_bar: ^0.3.4
  # firebase_storage: ^5.0.1
  # firebase_auth: ^0.18.3
  # firebase_auth: ^0.8.3
  # google_sign_in: ^4.0.1+1
  
  # cloud_firestore: ^0.9.7+2
  flutter_downloader: ^1.5.2
  # google_sign_in: ^4.5.6
  firebase_messaging: ^4.0.0+1
  geolocator: 5.0.1
  permission_handler: ^5.0.1+1
  provider: ^4.3.2+2
  carousel_slider: ^2.3.1
  uuid: ^2.0.0
  image: ^2.0.7
  animator: 0.1.4
  cupertino_icons: ^0.1.2
  path_provider: ^1.6.24
  
  timeago: 2.0.17
  cached_network_image: ^2.3.3
  flutter_svg: ^0.19.1
  dropdownfield: ^1.0.3
  url_launcher: ^5.7.10
  http: ^0.12.2
  
  form_field_validator: ^1.0.1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  cloud_firestore: ^0.13.7
  email_validator: ^1.0.6
  
  path: ^1.7.0
  states_rebuilder: 1.3.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

 

    
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-Medium.ttf
          style : italic
    - family: Alison
      fonts:
        - asset: assets/fonts/Allison_Script.ttf

   

  assets:
    - assets/images/google_signin_button.png
    - assets/images/upload.svg
    - assets/images/search.svg
    - assets/images/activity_feed.svg
    - assets/images/no_content.svg
    - assets/images/logo.svg
    - assets/images/logo2.png
